if ($programname == "pop-talk-chatbot") then {
    action(
        type="omfile"
        file="/var/log/pop-talk/chatbot.log"
        createDirs="on"
        dirCreateMode="0750"
        fileCreateMode="0640"
    )
    stop
}
